"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-10 14:11:15.790265

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import books_of_time.db.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_coverage_stats",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("collection_task_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column(
            "task_kind",
            sa.Enum(
                "fetch_video_info",
                "fetch_video_stats",
                "fetch_hot_comments",
                "fetch_latest_comments",
                "fetch_comment_replies",
                "fetch_media_asset",
                "discover_user_videos",
                "analyze_similar_media",
                name="taskkind",
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("pages_requested", sa.Integer(), nullable=False),
        sa.Column("pages_succeeded", sa.Integer(), nullable=False),
        sa.Column("items_observed", sa.Integer(), nullable=False),
        sa.Column("raw_payloads_saved", sa.BigInteger(), nullable=False),
        sa.Column("parse_errors", sa.Integer(), nullable=False),
        sa.Column("request_errors", sa.Integer(), nullable=False),
        sa.Column("frontier_reached", sa.Boolean(), nullable=True),
        sa.Column("frontier_missing", sa.Boolean(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("corrupted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_collection_coverage_run",
        "collection_coverage_stats",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        "idx_collection_coverage_target_time",
        "collection_coverage_stats",
        ["target_type", "target_id", sa.literal_column("finished_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_collection_coverage_task",
        "collection_coverage_stats",
        ["collection_task_id"],
        unique=False,
    )
    op.create_table(
        "collection_runs",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("tasks_started", sa.Integer(), nullable=False),
        sa.Column("tasks_succeeded", sa.Integer(), nullable=False),
        sa.Column("tasks_failed", sa.Integer(), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(
        "idx_collection_runs_run_id", "collection_runs", ["run_id"], unique=False
    )
    op.create_index(
        "idx_collection_runs_started_at",
        "collection_runs",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "collection_tasks",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "fetch_video_info",
                "fetch_video_stats",
                "fetch_hot_comments",
                "fetch_latest_comments",
                "fetch_comment_replies",
                "fetch_media_asset",
                "discover_user_videos",
                "analyze_similar_media",
                name="taskkind",
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("budget_cost", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "backoff",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "not_before",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column(
            "lease_until",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_collection_tasks_pick",
        "collection_tasks",
        ["status", "not_before", sa.literal_column("priority DESC"), "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_collection_tasks_target",
        "collection_tasks",
        ["target_type", "target_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_collection_tasks_active_idempotency_key",
        "collection_tasks",
        ["idempotency_key"],
        unique=True,
        sqlite_where=sa.text("status IN ('pending', 'running', 'backoff')"),
        postgresql_where=sa.text("status IN ('pending', 'running', 'backoff')"),
    )
    op.create_table(
        "comment_entities",
        sa.Column("rpid", sa.BigInteger(), nullable=False),
        sa.Column("oid", sa.BigInteger(), nullable=False),
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("root_rpid", sa.BigInteger(), nullable=True),
        sa.Column("parent_rpid", sa.BigInteger(), nullable=True),
        sa.Column("author_mid", sa.BigInteger(), nullable=True),
        sa.Column("author_name", sa.Text(), nullable=True),
        sa.Column("first_content", sa.Text(), nullable=True),
        sa.Column("first_content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "first_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("first_raw_payload_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("rpid"),
    )
    op.create_index(
        "idx_comment_entities_author_mid",
        "comment_entities",
        ["author_mid"],
        unique=False,
    )
    op.create_index(
        "idx_comment_entities_bvid_rpid",
        "comment_entities",
        ["bvid", "rpid"],
        unique=False,
    )
    op.create_table(
        "comment_observation_media",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("comment_observation_id", sa.BigInteger(), nullable=False),
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("rpid", sa.BigInteger(), nullable=False),
        sa.Column("media_source_id", sa.BigInteger(), nullable=False),
        sa.Column("media_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("raw_page_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_observation_id", "position"),
    )
    op.create_index(
        "idx_comment_obs_media_asset",
        "comment_observation_media",
        ["media_asset_id"],
        unique=False,
    )
    op.create_index(
        "idx_comment_obs_media_rpid",
        "comment_observation_media",
        ["rpid"],
        unique=False,
    )
    op.create_index(
        "idx_comment_obs_media_source",
        "comment_observation_media",
        ["media_source_id"],
        unique=False,
    )
    op.create_table(
        "comment_observations",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("rpid", sa.BigInteger(), nullable=False),
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("oid", sa.BigInteger(), nullable=False),
        sa.Column(
            "captured_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("raw_payload_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_page_observation_id", sa.BigInteger(), nullable=True),
        sa.Column("sort_mode", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("media_ordered_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("media_set_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("like_count", sa.BigInteger(), nullable=True),
        sa.Column("reply_count", sa.BigInteger(), nullable=True),
        sa.Column("author_mid", sa.BigInteger(), nullable=True),
        sa.Column("author_name", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_comment_observations_bvid_time",
        "comment_observations",
        ["bvid", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_comment_observations_raw_page",
        "comment_observations",
        ["raw_page_observation_id"],
        unique=False,
    )
    op.create_index(
        "idx_comment_observations_rpid_time",
        "comment_observations",
        ["rpid", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "comment_state_events",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("rpid", sa.BigInteger(), nullable=False),
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("previous_comment_observation_id", sa.BigInteger(), nullable=True),
        sa.Column("current_comment_observation_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column(
            "old_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "new_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_comment_state_events_current",
        "comment_state_events",
        ["current_comment_observation_id"],
        unique=False,
    )
    op.create_index(
        "idx_comment_state_events_rpid", "comment_state_events", ["rpid"], unique=False
    )
    op.create_table(
        "comment_visibility_events",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("rpid", sa.BigInteger(), nullable=False),
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("previous_comment_observation_id", sa.BigInteger(), nullable=True),
        sa.Column("current_comment_observation_id", sa.BigInteger(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("old_visibility", sa.Text(), nullable=True),
        sa.Column("new_visibility", sa.Text(), nullable=True),
        sa.Column("missing_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_comment_visibility_events_current",
        "comment_visibility_events",
        ["current_comment_observation_id"],
        unique=False,
    )
    op.create_index(
        "idx_comment_visibility_events_rpid",
        "comment_visibility_events",
        ["rpid"],
        unique=False,
    )
    op.create_index(
        "idx_comment_visibility_events_type",
        "comment_visibility_events",
        ["event_type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "frontier_states",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column("frontier_type", sa.Text(), nullable=False),
        sa.Column("frontier_rpid", sa.BigInteger(), nullable=True),
        sa.Column(
            "frontier_time",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column(
            "last_scan_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("last_scan_status", sa.Text(), nullable=True),
        sa.Column("last_scan_pages", sa.Integer(), nullable=False),
        sa.Column("last_scan_truncated", sa.Boolean(), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_type", "target_id", "frontier_type"),
    )
    op.create_table(
        "important_comment_watchlist",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("rpid", sa.BigInteger(), nullable=False),
        sa.Column("root_rpid", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reply_count", sa.BigInteger(), nullable=True),
        sa.Column("like_count", sa.BigInteger(), nullable=True),
        sa.Column("hot_position", sa.Integer(), nullable=True),
        sa.Column("last_comment_observation_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "first_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bvid", "rpid"),
    )
    op.create_index(
        "idx_important_watchlist_active",
        "important_comment_watchlist",
        ["active"],
        unique=False,
    )
    op.create_index(
        "idx_important_watchlist_priority",
        "important_comment_watchlist",
        [
            "active",
            sa.literal_column("priority DESC"),
            sa.literal_column("updated_at DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "idx_important_watchlist_rpid",
        "important_comment_watchlist",
        ["rpid"],
        unique=False,
    )
    op.create_table(
        "known_videos",
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column("source_mid", sa.Text(), nullable=True),
        sa.Column(
            "pubdate", books_of_time.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "first_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("bvid"),
    )
    op.create_table(
        "media_assets",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("blob_sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("pixel_sha256", sa.LargeBinary(length=32), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("file_ext", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("first_raw_page_id", sa.BigInteger(), nullable=True),
        sa.Column("download_raw_payload_id", sa.BigInteger(), nullable=True),
        sa.Column("phash", sa.BigInteger(), nullable=True),
        sa.Column("dhash", sa.BigInteger(), nullable=True),
        sa.Column("ahash", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_sha256"),
    )
    op.create_index("idx_media_assets_phash", "media_assets", ["phash"], unique=False)
    op.create_index(
        "idx_media_assets_pixel_sha256", "media_assets", ["pixel_sha256"], unique=False
    )
    op.create_table(
        "media_cluster_members",
        sa.Column("cluster_id", sa.BigInteger(), nullable=False),
        sa.Column("media_asset_id", sa.BigInteger(), nullable=False),
        sa.Column("distance_to_representative", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("cluster_id", "media_asset_id"),
    )
    op.create_table(
        "media_clusters",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("cluster_type", sa.Text(), nullable=False),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column("algorithm_version", sa.Text(), nullable=False),
        sa.Column("representative_asset_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "media_similarity_edges",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("media_asset_id_a", sa.BigInteger(), nullable=False),
        sa.Column("media_asset_id_b", sa.BigInteger(), nullable=False),
        sa.Column("similarity_type", sa.Text(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column("algorithm_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "media_asset_id_a",
            "media_asset_id_b",
            "similarity_type",
            "algorithm",
            "algorithm_version",
        ),
    )
    op.create_index(
        "idx_media_similarity_a",
        "media_similarity_edges",
        ["media_asset_id_a"],
        unique=False,
    )
    op.create_index(
        "idx_media_similarity_b",
        "media_similarity_edges",
        ["media_asset_id_b"],
        unique=False,
    )
    op.create_table(
        "media_sources",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("source_url_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("normalized_url_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("normalized_url", sa.Text(), nullable=True),
        sa.Column("media_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("fetch_status", sa.Text(), nullable=False),
        sa.Column("fetch_error_type", sa.Text(), nullable=True),
        sa.Column("fetch_error_message", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("first_raw_page_id", sa.BigInteger(), nullable=True),
        sa.Column("last_raw_page_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "source_url_hash"),
    )
    op.create_index(
        "idx_media_sources_asset", "media_sources", ["media_asset_id"], unique=False
    )
    op.create_index(
        "idx_media_sources_fetch_status",
        "media_sources",
        ["fetch_status"],
        unique=False,
    )
    op.create_index(
        "idx_media_sources_normalized_url",
        "media_sources",
        ["normalized_url_hash"],
        unique=False,
    )
    op.create_table(
        "raw_page_observations",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("raw_payload_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "captured_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "request_type",
            sa.Enum(
                "bilibili:video_info",
                "bilibili:video_stats",
                "bilibili:comment_hot",
                "bilibili:comment_latest",
                "bilibili:comment_reply",
                "bilibili:media_image",
                "bilibili:user_video_list",
                "bilibili:search_video",
                "bilibili:default",
                name="bilibilirequesttype",
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("sort_mode", sa.Text(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_raw_page_observations_raw_payload",
        "raw_page_observations",
        ["raw_payload_id"],
        unique=False,
    )
    op.create_index(
        "idx_raw_page_observations_target_time",
        "raw_page_observations",
        ["target_type", "target_id", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "raw_payloads",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "captured_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "request_type",
            sa.Enum(
                "bilibili:video_info",
                "bilibili:video_stats",
                "bilibili:comment_hot",
                "bilibili:comment_latest",
                "bilibili:comment_reply",
                "bilibili:media_image",
                "bilibili:user_video_list",
                "bilibili:search_video",
                "bilibili:default",
                name="bilibilirequesttype",
            ),
            nullable=False,
        ),
        sa.Column("method", sa.String(length=12), nullable=False),
        sa.Column("url_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("params_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("payload_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("compressed_size", sa.BigInteger(), nullable=False),
        sa.Column("uncompressed_size", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_raw_payloads_request_type_time",
        "raw_payloads",
        ["request_type", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_raw_payloads_time",
        "raw_payloads",
        [sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "request_backoff_states",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum(
                "bilibili:video_info",
                "bilibili:video_stats",
                "bilibili:comment_hot",
                "bilibili:comment_latest",
                "bilibili:comment_reply",
                "bilibili:media_image",
                "bilibili:user_video_list",
                "bilibili:search_video",
                "bilibili:default",
                name="bilibilirequesttype",
            ),
            nullable=False,
        ),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("error_kind", sa.Text(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("retry_after_seconds", sa.Integer(), nullable=True),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_failed_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_failed_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "backoff_until",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("last_message", sa.Text(), nullable=True),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "request_type", "scope"),
    )
    op.create_index(
        "idx_request_backoff_error_time",
        "request_backoff_states",
        ["error_kind", sa.literal_column("last_failed_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_request_backoff_key",
        "request_backoff_states",
        ["platform", "request_type", "scope"],
        unique=False,
    )
    op.create_index(
        "idx_request_backoff_until",
        "request_backoff_states",
        ["backoff_until"],
        unique=False,
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("job_key", sa.Text(), nullable=False),
        sa.Column(
            "job_kind",
            sa.Enum(
                "uid_discovery",
                "video_snapshot_sweep",
                "daily_terminal_snapshot",
                name="scheduledjobkind",
            ),
            nullable=False,
        ),
        sa.Column("schedule_seconds", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "next_run_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column(
            "lease_until",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_started_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_succeeded_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_failed_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error_type", sa.String(length=120), nullable=True),
        sa.Column("last_error_message", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_key"),
    )
    op.create_index(
        "idx_scheduled_jobs_due",
        "scheduled_jobs",
        ["enabled", "next_run_at", sa.literal_column("priority DESC")],
        unique=False,
    )
    op.create_index(
        "idx_scheduled_jobs_lease", "scheduled_jobs", ["lease_until"], unique=False
    )
    op.create_table(
        "service_instances",
        sa.Column("instance_id", sa.Text(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column(
            "roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "heartbeat_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "stopped_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("last_error_type", sa.String(length=120), nullable=True),
        sa.Column("last_error_message", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最后更新时间",
        ),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    op.create_index(
        "idx_service_instances_started_at",
        "service_instances",
        [sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_service_instances_status_heartbeat",
        "service_instances",
        ["status", sa.literal_column("heartbeat_at DESC")],
        unique=False,
    )
    op.create_table(
        "video_availability_snapshots",
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column(
            "captured_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("bili_code", sa.BigInteger(), nullable=True),
        sa.Column("bili_message", sa.Text(), nullable=True),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("raw_payload_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("bvid", "captured_at"),
    )
    op.create_index(
        "idx_video_availability_snapshots_bvid_time",
        "video_availability_snapshots",
        ["bvid", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_video_availability_snapshots_status_time",
        "video_availability_snapshots",
        ["status", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "video_info_snapshots",
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column(
            "captured_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_mid", sa.BigInteger(), nullable=True),
        sa.Column("owner_name", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("raw_payload_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("bvid", "captured_at"),
    )
    op.create_index(
        "idx_video_info_snapshots_bvid_time",
        "video_info_snapshots",
        ["bvid", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "video_metric_snapshots",
        sa.Column("bvid", sa.Text(), nullable=False),
        sa.Column(
            "captured_at",
            books_of_time.db.types.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("view_count", sa.BigInteger(), nullable=True),
        sa.Column("like_count", sa.BigInteger(), nullable=True),
        sa.Column("coin_count", sa.BigInteger(), nullable=True),
        sa.Column("favorite_count", sa.BigInteger(), nullable=True),
        sa.Column("share_count", sa.BigInteger(), nullable=True),
        sa.Column("reply_count", sa.BigInteger(), nullable=True),
        sa.Column("danmaku_count", sa.BigInteger(), nullable=True),
        sa.Column("raw_payload_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("bvid", "captured_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_metric_snapshots")
    op.drop_index(
        "idx_video_info_snapshots_bvid_time", table_name="video_info_snapshots"
    )
    op.drop_table("video_info_snapshots")
    op.drop_index(
        "idx_video_availability_snapshots_status_time",
        table_name="video_availability_snapshots",
    )
    op.drop_index(
        "idx_video_availability_snapshots_bvid_time",
        table_name="video_availability_snapshots",
    )
    op.drop_table("video_availability_snapshots")
    op.drop_index(
        "idx_service_instances_status_heartbeat", table_name="service_instances"
    )
    op.drop_index("idx_service_instances_started_at", table_name="service_instances")
    op.drop_table("service_instances")
    op.drop_index("idx_scheduled_jobs_lease", table_name="scheduled_jobs")
    op.drop_index("idx_scheduled_jobs_due", table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index("idx_request_backoff_until", table_name="request_backoff_states")
    op.drop_index("idx_request_backoff_key", table_name="request_backoff_states")
    op.drop_index("idx_request_backoff_error_time", table_name="request_backoff_states")
    op.drop_table("request_backoff_states")
    op.drop_index("idx_raw_payloads_time", table_name="raw_payloads")
    op.drop_index("idx_raw_payloads_request_type_time", table_name="raw_payloads")
    op.drop_table("raw_payloads")
    op.drop_index(
        "idx_raw_page_observations_target_time", table_name="raw_page_observations"
    )
    op.drop_index(
        "idx_raw_page_observations_raw_payload", table_name="raw_page_observations"
    )
    op.drop_table("raw_page_observations")
    op.drop_index("idx_media_sources_normalized_url", table_name="media_sources")
    op.drop_index("idx_media_sources_fetch_status", table_name="media_sources")
    op.drop_index("idx_media_sources_asset", table_name="media_sources")
    op.drop_table("media_sources")
    op.drop_index("idx_media_similarity_b", table_name="media_similarity_edges")
    op.drop_index("idx_media_similarity_a", table_name="media_similarity_edges")
    op.drop_table("media_similarity_edges")
    op.drop_table("media_clusters")
    op.drop_table("media_cluster_members")
    op.drop_index("idx_media_assets_pixel_sha256", table_name="media_assets")
    op.drop_index("idx_media_assets_phash", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_table("known_videos")
    op.drop_index(
        "idx_important_watchlist_rpid", table_name="important_comment_watchlist"
    )
    op.drop_index(
        "idx_important_watchlist_priority", table_name="important_comment_watchlist"
    )
    op.drop_index(
        "idx_important_watchlist_active", table_name="important_comment_watchlist"
    )
    op.drop_table("important_comment_watchlist")
    op.drop_table("frontier_states")
    op.drop_index(
        "idx_comment_visibility_events_type", table_name="comment_visibility_events"
    )
    op.drop_index(
        "idx_comment_visibility_events_rpid", table_name="comment_visibility_events"
    )
    op.drop_index(
        "idx_comment_visibility_events_current", table_name="comment_visibility_events"
    )
    op.drop_table("comment_visibility_events")
    op.drop_index("idx_comment_state_events_rpid", table_name="comment_state_events")
    op.drop_index("idx_comment_state_events_current", table_name="comment_state_events")
    op.drop_table("comment_state_events")
    op.drop_index(
        "idx_comment_observations_rpid_time", table_name="comment_observations"
    )
    op.drop_index(
        "idx_comment_observations_raw_page", table_name="comment_observations"
    )
    op.drop_index(
        "idx_comment_observations_bvid_time", table_name="comment_observations"
    )
    op.drop_table("comment_observations")
    op.drop_index(
        "idx_comment_obs_media_source", table_name="comment_observation_media"
    )
    op.drop_index("idx_comment_obs_media_rpid", table_name="comment_observation_media")
    op.drop_index("idx_comment_obs_media_asset", table_name="comment_observation_media")
    op.drop_table("comment_observation_media")
    op.drop_index("idx_comment_entities_bvid_rpid", table_name="comment_entities")
    op.drop_index("idx_comment_entities_author_mid", table_name="comment_entities")
    op.drop_table("comment_entities")
    op.drop_index(
        "uq_collection_tasks_active_idempotency_key",
        table_name="collection_tasks",
        sqlite_where=sa.text("status IN ('pending', 'running', 'backoff')"),
        postgresql_where=sa.text("status IN ('pending', 'running', 'backoff')"),
    )
    op.drop_index("idx_collection_tasks_target", table_name="collection_tasks")
    op.drop_index("idx_collection_tasks_pick", table_name="collection_tasks")
    op.drop_table("collection_tasks")
    op.drop_index("idx_collection_runs_started_at", table_name="collection_runs")
    op.drop_index("idx_collection_runs_run_id", table_name="collection_runs")
    op.drop_table("collection_runs")
    op.drop_index(
        "idx_collection_coverage_task", table_name="collection_coverage_stats"
    )
    op.drop_index(
        "idx_collection_coverage_target_time", table_name="collection_coverage_stats"
    )
    op.drop_index("idx_collection_coverage_run", table_name="collection_coverage_stats")
    op.drop_table("collection_coverage_stats")
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in (
            "bilibilirequesttype",
            "scheduledjobkind",
            "taskkind",
            "taskstatus",
        ):
            postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
